[build]
builder = "nixpacks"

[build.nixpacks]
aptPkgs = []

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn mini_ecom.wsgi --bind 0.0.0.0:$PORT"

[general]
root = "mini_ecom2"
